/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2021-07-07 00:21:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/dbConnection.jsp", Long.valueOf(1621992416000L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1565185658000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1565186624000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	/* 한글 깨짐 방지 */
	request.setCharacterEncoding("UTF-8");

	/* DB 접속 */
	String user = "sqlDB"; // oracle 계정
	String pw = "1234";   // oracle 비밀번호
	String url = "jdbc:oracle:thin:@localhost:1521:xe"; // 그대로 사용
	String sql = "";
	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection conn = DriverManager.getConnection(url, user, pw);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/common.css\" />\r\n");
      out.write("<title>쇼핑몰 회원 관리</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<h3 class=\"logo\">쇼핑몰 회원 관리</h3>\r\n");
      out.write("\t\t<div class=\"gnb\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"./index.jsp\">회원등록</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"./list.jsp\">회원목록 조회/수정</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"./money.jsp\">회원매출조회</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"./index.jsp\">홈으로</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"content\">");
      out.write('\r');
      out.write('\n');

	/* next value 가져오기 */
	sql = "SELECT custno from member_tbl_02 where rownum <= 1 order by custno desc";
	ResultSet res = conn.prepareStatement(sql).executeQuery();
	int custno = 10001;
	if (res.next()) custno = res.getInt(1)+1;

      out.write("\r\n");
      out.write("<h2>홈쇼핑 회원 등록</h2>\r\n");
      out.write("<form action=\"./action.jsp\" method=\"post\">\r\n");
      out.write("\t<!-- action.jsp에서 actino 값을 통하여 sql을 handling 한다. -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"action\" value=\"insert\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t<col width=\"80%\">\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>회원번호(자동발생)</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" size=\"20\" value=\"");
      out.print( custno );
      out.write("\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>회원성명</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"custname\" size=\"20\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>회원전화</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"phone\" size=\"30\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>회원주소</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"address\" size=\"40\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>가입일자</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"joindate\" size=\"20\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t고객등급\r\n");
      out.write("\t\t\t\t<br>(A:VIP, B:일반, C:직원)\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"grade\" size=\"20\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>도시코드</th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"city\" size=\"20\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div class=\"btn_group\">\r\n");
      out.write("\t\t<button type=\"submit\">등록</button>\r\n");
      out.write("\t\t<button type=\"button\">조회</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\tcopyright &copy; 2019 junil.hwang all right reserved.\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
